voting-app:
  build: ./voting-app/.
  ports:
    - "5000:80"
  links:
    - redis

redis:
  image: hypriot/rpi-redis
  ports: ["6379"]

worker:
  build: ./worker
  links:
    - redis
    - db

db:
  image: randyp/rpi-postgres:9.4.0
  volumes:
    - "myvolume:/var/lib/postgresql/data"

result-app:
  build: ./result-app/.
  ports:
    - "5001:80"
  links:
    - db
